app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
Route::get('mail', 'MailController@sendMail');
Route::get('test', 'TestController@index');
/* PAGES */
Route::post('changelocale', ['as' => 'changelocale', 'uses' => 'TranslationController@changeLocale']);
Route::post('dodaj', ['as' => 'dodaj.software', 'uses' => 'AddSoftwareController@addSoftware']);
Route::post('contact', 'ContactController@contact');
Route::get('RSS', 'RssFeedController@getRSS');
Route::get('/o-nama', 'PageController@aboutUs');
Route::get('str/sto-se-skida', 'PageController@whatIsDownloaded');
Route::get('/dodaj', 'PageController@addSoftware');
Route::get('/logout', 'Auth\AuthController@logout');
Route::get('/top-50', 'PageController@topPrograms');

Route::get('/downloads/{id}', ['uses' => 'DownloadController@download', 'as' => 'download.software']);
Route::get('/downloads/m/{id}', ['uses' => 'DownloadController@download', 'as' => 'download.software.mirror']);
Route::get('/downloads/download/{id}', ['uses' => 'DownloadController@downloadSoftware', 'as' => 'download.software.path']);
Route::get('/downloads/download/server/{id}', ['uses' => 'DownloadController@downloadSoftwareFromServer', 'as' => 'download.software.path.server']);

Route::get('/search', 'SearchController@index');
Route::get('/search/{software}', 'SearchController@show');
/* API */
Route::group(['prefix' => 'api/v1'], function() {
    Route::get('/search/{name}', 'Api\SearchSoftwareController@searchByName');
    Route::get('/getSoftwares/{name}', 'Api\SearchSoftwareController@getSoftwaresByName');
    Route::post('/cookie', 'Api\SearchSoftwareController@setCookieExperience');
});

Route::group(['middleware' => 'web'], function () {

    Route::auth();

    Route::get('home', ['as' => 'home', 'uses' => function () {
        return view('home');
    }]);

    Route::get('social/login/redirect/{provider}', ['uses' => 'Auth\AuthController@redirectToProvider', 'as' => 'social.login']);
    Route::get('social/login/{provider}', 'Auth\AuthController@handleProviderCallback');

    Route::get('str/software_list', 'FavoritesController@index');
    Route::get('str/software_list/delete/all', ['uses' => 'FavoritesController@deleteAll', 'as' => 'delete.favorite.all']);
    Route::get('str/software_list/delete/{id}', ['uses' => 'FavoritesController@delete', 'as' => 'delete.favorite']);
    Route::get('str/software_list/add/{id}', ['uses' => 'FavoritesController@addFavorite', 'as' => 'add.favorite']);

    Route::get('software/mark/add', ['uses' => 'MarksController@addMark', 'as' => 'add.mark']);



    # ADMIN SECTION
    Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {

        Route::get('home', 'HomeController@index');

        # CATEGORIES
        Route::resource('kategorije', 'Admin\CategoryController');

        # USERS
        Route::resource('korisnici', 'Admin\UserController');

        # SOFTWARE
        Route::resource('software', 'Admin\SoftwareController');
        Route::post('software/search', 'Admin\SoftwareController@search');

        #DEAD LINKS
        Route::get('deadlinks', 'Admin\DeadLinksController@index');
        Route::get('deadlinks/check', 'Admin\DeadLinksController@checkLinks');
        Route::post('deadlinks/update/{id}', ['uses' => 'Admin\DeadLinksController@updateLink', 'as' => 'deadlinks.update']);
        Route::delete('deadlinks/delete/{id}', ['uses' => 'Admin\DeadLinksController@deleteSoftware', 'as' => 'deadlinks.delete']);
        Route::post('deadlinks/report/{id}', ['uses' => 'Admin\DeadLinksController@reportBrokenLink', 'as' => 'deadlinks.report']);

        #PROGRAM OF WEEK
        Route::get('week/programs', 'Admin\ProgramWeekController@index');
        Route::post('week/programs/add/{id}', ['uses' => 'Admin\ProgramWeekController@addProgram', 'as' => 'week.program.add']);

        #USER SOFTWARE
        Route::get('korisnici-software', 'AddSoftwareController@showUserSoftwares');
        Route::delete('korisnici-software/delete/{id}', ['uses' => 'AddSoftwareController@deleteUserSoftware', 'as' => 'user.software.delete']);
        Route::get('korisnici-software/accept/{id}', ['uses' => 'AddSoftwareController@acceptUserSoftware', 'as' => 'user.software.accept']);

        #CONTENT
        Route::get('content', 'Admin\ContentController@index');
        Route::post('content', 'Admin\ContentController@saveContent');

    });

    Route::get('/{category?}', 'PageController@home');
    Route::get('/{category}/{software}', 'PageController@details');

});

app/Software.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Software extends Model
{
    protected $table = 'software';

    protected $guarded = [];

    public $timestamps = false;

    public function category()
    {
        return $this->belongsTo('App\Category', 'kategorija');
    }

    public function users() {
        return $this->belongsToMany('App\User', 'users', 'korisnici_id', 'software_id');
    }
}

app/Http/Controllers/Admin/SoftwareController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\ImageController;
use App\Software;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class SoftwareController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $softwares = Software::orderBy('dodano', 'desc')->paginate(10);
        $searching = false;
        return view('admin.software.index', compact('softwares', 'searching'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all(['id', 'imeKategorije']);
        return view('admin.software.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $software = new Software();
        $software->ime = $request->ime;
        $software->imeUrl = parseCategoryName($request->ime);
        $software->kategorija = $request->kategorija;
        $software->autor = $request->autor;
        $software->homepage = $request->homepage;
        $software->verzija = $request->verzija;
        $software->licenca = $request->licenca;
        $software->platforma = $request->platforma;
        if(!empty($request['path'])) {
            $software->velicina = getRemoteFileSize($request['path']);
        }
        $software->sucelje = $request->sucelje;
        $software->mogucnosti = $request->mogucnosti;
        $software->jednostavnost = $request->jednostavnost;
        $software->nasaOcjena = $request->nasaOcjena;
        if(empty($request->preporuka)) {
            $software->preporuka = 0;
        } else {
            $software->preporuka = $request->preporuka;
        }
        $software->path = $request->path;
        $software->opis = $request->opis;
        $software->opisEn = $request->opisEn;
        $software->skidanja = $request->skidanja;
        $software->velicina = $request->velicina;
        if($request->updated == false) {
            $vrijeme = time();
            $software->stvoreno = $vrijeme;
            $software->dodano = $vrijeme;
        } else {
            $software->stvoreno = strtotime($request->updated);
            $software->dodano = strtotime($request->updated);
        }
        $file = $request->file('dl_file');
        if(isset($file)) {
            $software->server_path = $file->getClientOriginalName();
            $software->mime = $file->getClientMimeType();
            $file->move('download', $file->getClientOriginalName());
        }

        if($_FILES['file']['name'] == '') {
            return back()->with('message', 'Slika je obavezna');
        }
        $rand = time();
        $rand .= rand(0,9);
        $rand .= rand(0,9);
        $rand .= rand(0,9);
        $software->rand = $rand;
        $folder = public_path() . "/slike";
        $arr = explode(".", $_FILES["file"]['name']);
        $ext = $arr[count($arr) - 1];
        $ekstenzije = array("jpg","JPG","gif","GIF","jpeg","JPEG","png","PNG");
        if(in_array($ext, $ekstenzije)){
            $slika = new ImageController();
            $slika ->upload($folder);
            $slika->createThumb($folder, 200, 122);
            $path = substr($slika -> getPath(), 9,strlen($slika -> getPath()));
            $software->slika = $slika->getImagePathName();
        }
        else{
            return back()->with('message', "Ekstenzija {$ext} nije dozvoljena!");
        }
        $software->save();
        return redirect('admin/software');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $software = Software::find($id);
        $categories = Category::all();
        return view('admin.software.edit', compact('software', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $software = Software::find($id);
        $software->ime = $request->ime;
        $software->imeUrl = parseCategoryName($request->ime);
        $software->kategorija = $request->kategorija;
        $software->autor = $request->autor;
        $software->homepage = $request->homepage;
        $software->verzija = $request->verzija;
        $software->licenca = $request->licenca;
        $software->platforma = $request->platforma;
        $software->sucelje = $request->sucelje;
        $software->mogucnosti = $request->mogucnosti;
        $software->jednostavnost = $request->jednostavnost;
        $software->nasaOcjena = $request->nasaOcjena;
        $software->preporuka = $request->preporuka;
        $software->path = $request->path;
        $software->opis = $request->opis;
        $software->opisEn = $request->opisEn;
        $software->skidanja = $request->skidanja;
        $software->velicina = $request->velicina;
        if($request->updated == false) {
            $vrijeme = time();
            $software->stvoreno = $vrijeme;
            $software->dodano = $vrijeme;
        } else {
            $software->stvoreno = strtotime($request->updated);
            $software->dodano = strtotime($request->updated);
        }
        $file = $request->file('dl_file');
        if(isset($file)) {
            $software->server_path = $file->getClientOriginalName();
            $software->mime = $file->getClientMimeType();
            $file->move('download', $file->getClientOriginalName());
        }
        $folder = public_path() . "/slike";
        $arr = explode(".", $_FILES["file"]['name']);
        $ext = $arr[count($arr) - 1];
        $ekstenzije = array("jpg","JPG","gif","GIF","jpeg","JPEG","png","PNG");
        if(in_array($ext, $ekstenzije)){
            $slika = new ImageController();
            $slika -> upload($folder);
            $slika->createThumb($folder, 200, 122);
            $path = substr($slika -> getPath(), 9,strlen($slika -> getPath()));
            $software->slika = $slika->getImagePathName();
        }
        $software->updated = date('Y-m-d H:i:s', time());
        $software->save();
        return redirect('admin/software');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Software::findOrFail($id)->delete();
        return redirect('admin/software');
    }

    /**
     * Search software by given name
     *
     * @param Request $request
     */
    public function search(Request $request)
    {
        $searching = true;
        $searchedTerm = '%' . $request['ime'] . '%';
        $softwares = Software::where('ime', 'LIKE', $searchedTerm)->get();
        return view('admin.software.index', compact('softwares', 'searching'));
    }
}

resources/views/admin/software/create.blade.php
@extends('admin.default.layout')

@section('content')
    <div class="container">
        <h1>Dodaj software</h1>
        @if (session('message'))
            <div class="alert alert-danger">
                {{ session('message') }}
            </div>
        @endif
        <form method="POST" action="{{ url('admin/software') }}" enctype="multipart/form-data">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <input type="hidden" name="_token" value="{!! csrf_token() !!}">
            <div class="form-group">
                <label for="ime">Ime programa:</label>
                <input type="text" name="ime" class="form-control">
            </div>
            <div class="form-group">
                <label for="kategorija">Kategorija:</label>
                <select name="kategorija" class="form-control">
                    <option value="">Odaberi kategoriju</option>
                    @foreach($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->imeKategorije }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="autor">Autor:</label>
                <input type="text" name="autor" class="form-control">
            </div>
            <div class="form-group">
                <label for="username">Homepage:</label>
                <input type="text" name="homepage" class="form-control">
            </div>
            <div class="form-group">
                <label for="username">Verzija:</label>
                <input type="text" name="verzija" class="form-control">
            </div>
            <div class="form-group">
                <label for="licenca">Licenca:</label>
                <select name="licenca" id="licenca" class="form-control">
                    <option value="Freeware" selected="selected">Freeware</option>
                    <option value="Shareware">Shareware</option>
                    <option value="Demo">Demo</option>
                    <option value="Trial">Trial</option>
                    <option value="Adware">Adware</option>
                </select>
            </div>
            <div class="form-group">
                <label for="platforma">Platforma:</label>
                <select name="platforma" id="platforma" class="form-control">
                    <option value="Linux">Linux</option>
                    <option value="Windows x86">Windows x86</option>
                    <option value="Win 7,Win 8, Win 10" selected="selected">Win 7,Win 8, Win 10</option>
                    <option value="Windows x64">Windows x64</option>
                    <option value="Macintosh">Macintosh</option>
                </select>
            </div>
            <div class="form-group">
                <label for="sucelje">Sučelje:</label>
                <select name="sucelje" id="platforma" class="form-control">
                    <option value="1">1/5</option>
                    <option value="2">2/5</option>
                    <option value="3">3/5</option>
                    <option value="4">4/5</option>
                    <option value="5">5/5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="mogucnosti">Mogućnosti:</label>
                <select name="mogucnosti" id="platforma" class="form-control">
                    <option value="1">1/5</option>
                    <option value="2">2/5</option>
                    <option value="3">3/5</option>
                    <option value="4">4/5</option>
                    <option value="5">5/5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="jednostavnost">Jednostavnost:</label>
                <select name="jednostavnost" id="platforma" class="form-control">
                    <option value="1">1/5</option>
                    <option value="2">2/5</option>
                    <option value="3">3/5</option>
                    <option value="4">4/5</option>
                    <option value="5">5/5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="nasaOcjena">Naša ocjena:</label>
                <select name="nasaOcjena" id="platforma" class="form-control">
                    <option value="1">1/5</option>
                    <option value="2">2/5</option>
                    <option value="3">3/5</option>
                    <option value="4">4/5</option>
                    <option value="5">5/5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="preporuka">Preporuka:</label>
                <input type="checkbox" value="1" class="form-control" name="preporuka">
            </div>
            <div class="form-group">
                <label for="path">Path:</label>
                <input type="text" class="form-control" name="path">
            </div>
            <div class="form-group">
                <label for="file">Upload file (ako nema path):</label>
                <input type="file" class="form-control" name="dl_file">
            </div>
            <div class="form-group">
                <label for="path">Opis HR:</label>
                <textarea name="opis" class="form-control" rows="10"></textarea>
            </div>
            <div class="form-group">
                <label for="path">Opis ENG:</label>
                <textarea name="opisEn" class="form-control" rows="10"></textarea>
            </div>
            <div class="form-group">
                <label for="file">Slika:</label>
                <input type="file" class="form-control" name="file" size="80">
            </div>
            <div class="form-group">
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker6'>
                        <input type='text' class="form-control" name="updated" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="path">Skidanja:</label>
                <input type="text" class="form-control" name="skidanja">
            </div>
                <div class="form-group">
                    <label for="path">Veličina (U BAJTOVIMA):</label>
                    <input type="text" class="form-control" name="velicina">
                </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary form-control">Dodaj</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/software/edit.blade.php
@extends('admin.default.layout')

@section('content')
    <div class="container">
        <h1>Ažuriraj software</h1>
        <form method="POST" action="{{ route('admin.software.update', array($software->id)) }}" enctype="multipart/form-data">
            <input type="hidden" name="_method" value="PUT">
            <input type="hidden" name="_token" value="{!! csrf_token() !!}">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="form-group">
                <label for="ime">Ime programa:</label>
                <input type="text" name="ime" class="form-control" value="{{ $software->ime }}">
            </div>
            <div class="form-group">
                <label for="kategorija">Kategorija:</label>
                <select name="kategorija" class="form-control">
                    <option value="">Odaberi kategoriju</option>
                    @foreach($categories as $category)
                        @if($category->id == $software->kategorija)
                            <option selected value="{{ $category->id }}">{{ $category->imeKategorije }}</option>
                        @endif
                        <option value="{{ $category->id }}">{{ $category->imeKategorije }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="autor">Autor:</label>
                <input type="text" name="autor" class="form-control" value="{{ $software->autor }}">
            </div>
            <div class="form-group">
                <label for="username">Homepage:</label>
                <input type="text" name="homepage" class="form-control" value="{{ $software->homepage }}">
            </div>
            <div class="form-group">
                <label for="username">Verzija:</label>
                <input type="text" name="verzija" class="form-control" value="{{ $software->verzija }}">
            </div>
            <div class="form-group">
                <label for="licenca">Licenca:</label>
                <select name="licenca" id="licenca" class="form-control">
                    <option value="{{ $software->licenca }}" selected>{{ $software->licenca }}</option>
                    <option value="Freeware">Freeware</option>
                    <option value="Shareware">Shareware</option>
                    <option value="Demo">Demo</option>
                    <option value="Trial">Trial</option>
                    <option value="Adware">Adware</option>
                </select>
            </div>
            <div class="form-group">
                <label for="platforma">Platforma:</label>
                <select name="platforma" id="platforma" class="form-control">
                    <option value="{{ $software->platforma }}" selected>{{ $software->platforma }}</option>
                    <option value="Linux">Linux</option>
                    <option value="Windows x86">Windows x86</option>
                    <option value="Win 7,Win 8, Win 10" selected="selected">Win 7,Win 8, Win 10</option>
                    <option value="Windows x64">Windows x64</option>
                    <option value="Macintosh">Macintosh</option>
                </select>
            </div>
            <div class="form-group">
                <label for="sucelje">Sučelje:</label>
                <select name="sucelje" id="platforma" class="form-control">
                    <option value="{{ $software->sucelje }}" selected>{{ $software->sucelje }}</option>
                    <option value="1">1/5</option>
                    <option value="2">2/5</option>
                    <option value="3">3/5</option>
                    <option value="4">4/5</option>
                    <option value="5">5/5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="mogucnosti">Mogućnosti:</label>
                <select name="mogucnosti" id="platforma" class="form-control">
                    <option value="{{ $software->mogucnosti }}" selected>{{ $software->mogucnosti }}</option>
                    <option value="1">1/5</option>
                    <option value="2">2/5</option>
                    <option value="3">3/5</option>
                    <option value="4">4/5</option>
                    <option value="5">5/5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="jednostavnost">Jednostavnost:</label>
                <select name="jednostavnost" id="platforma" class="form-control">
                    <option value="{{ $software->jednostavnost }}" selected>{{ $software->jednostavnost }}</option>
                    <option value="1">1/5</option>
                    <option value="2">2/5</option>
                    <option value="3">3/5</option>
                    <option value="4">4/5</option>
                    <option value="5">5/5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="nasaOcjena">Naša ocjena:</label>
                <select name="nasaOcjena" id="platforma" class="form-control">
                    <option value="{{ $software->nasaOcjena }}" selected>{{ $software->nasaOcjena }}</option>
                    <option value="1">1/5</option>
                    <option value="2">2/5</option>
                    <option value="3">3/5</option>
                    <option value="4">4/5</option>
                    <option value="5">5/5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="preporuka">Preporuka:</label>
                @if($software->preporuka == 1)
                    <input type="checkbox" value="1" class="form-control" name="preporuka" checked>
                @else
                    <input type="checkbox" value="1" class="form-control" name="preporuka">
                @endif
            </div>
            <div class="form-group">
                <label for="path">Path:</label>
                <input type="text" class="form-control" name="path" value="{{ $software->path }}">
            </div>
            <div class="form-group">
                <label for="file">Upload file (ako nema path):</label>
                <input type="file" class="form-control" name="dl_file">
            </div>
            <div class="form-group">
                <label for="path">Opis HR:</label>
                <textarea name="opis" class="form-control" rows="10">{{ $software->opis }}</textarea>
            </div>
            <div class="form-group">
                <label for="path">Opis ENG:</label>
                <textarea name="opisEn" class="form-control" rows="10">{{ $software->opisEn }}</textarea>
            </div>
            <div class="form-group">
                <label for="file">Slika:</label>
                <input type="file" class="form-control" name="file" size="80">
            </div>
            <div class="form-group">
                <label for="path">Vrijeme obavljivanja:</label>
                <input type="text" name="updated" value="{{ date('Y-m-d H:i:s', $software->dodano) }}">
            </div>
            <div class="form-group">
                <label for="path">Skidanja:</label>
                <input type="text" class="form-control" name="skidanja" value="{{ $software->skidanja }}">
            </div>
            <div class="form-group">
                <label for="path">Veličina (U BAJTOVIMA):</label>
                <input type="text" class="form-control" name="velicina" value="{{ $software->velicina }}">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary form-control">Ažuriraj</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/software/index.blade.php
@extends('admin.default.layout')

@section('content')
    <div class="container">
        <h1>Software</h1>
        <a href="{{url('admin/software/create')}}" class="btn btn-success">Dodaj software</a>
        <form method="post" action="{{ url('admin/software/search') }}">
            <input type="hidden" name="_token" value="{!! csrf_token() !!}">
            <input type="search" placeholder="upiši ime software..." name="ime">
            <input type="submit" value="Pretraži..." class="btn-info">
        </form>

        <hr>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>ID</th>
                <th>Ime programa</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($softwares as $software)
                <tr>
                    <td>{{ $software->id }}</td>
                    <td>{{ $software->ime }}</td>
                    <td><a href="{{route('admin.software.edit',$software->id)}}" class="btn btn-warning">Ažuriraj</a></td>
                    <td>
                        <form action="{{ route('admin.software.destroy', [$software->id]) }}" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button type="submit" class="btn btn-danger">Obriši</button>
                        </form>
                    </td>
                    <td>
                        <form action="{{ route('week.program.add', [$software->id]) }}" method="POST">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input type="text" name="ime" value="{{ $software->ime }}" hidden>
                            <button type="submit" class="btn btn-primary">Označi kao program tjedna</button>
                        </form>
                    </td>
                </tr>
            @endforeach

            </tbody>

        </table>
        @if($searching === true)
            @else
        <div style="text-align: center">
            {!! $softwares->render() !!}
        </div>
            @endif

    </div>
@endsection