app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
Route::get('mail', 'MailController@sendMail');
Route::get('test', 'TestController@index');
/* PAGES */
Route::post('changelocale', ['as' => 'changelocale', 'uses' => 'TranslationController@changeLocale']);
Route::post('dodaj', ['as' => 'dodaj.software', 'uses' => 'AddSoftwareController@addSoftware']);
Route::post('contact', 'ContactController@contact');
Route::get('RSS', 'RssFeedController@getRSS');
Route::get('/o-nama', 'PageController@aboutUs');
Route::get('str/sto-se-skida', 'PageController@whatIsDownloaded');
Route::get('/dodaj', 'PageController@addSoftware');
Route::get('/logout', 'Auth\AuthController@logout');
Route::get('/top-50', 'PageController@topPrograms');

Route::get('/downloads/{id}', ['uses' => 'DownloadController@download', 'as' => 'download.software']);
Route::get('/downloads/m/{id}', ['uses' => 'DownloadController@download', 'as' => 'download.software.mirror']);
Route::get('/downloads/download/{id}', ['uses' => 'DownloadController@downloadSoftware', 'as' => 'download.software.path']);
Route::get('/downloads/download/server/{id}', ['uses' => 'DownloadController@downloadSoftwareFromServer', 'as' => 'download.software.path.server']);

Route::get('/search', 'SearchController@index');
Route::get('/search/{software}', 'SearchController@show');
/* API */
Route::group(['prefix' => 'api/v1'], function() {
    Route::get('/search/{name}', 'Api\SearchSoftwareController@searchByName');
    Route::get('/getSoftwares/{name}', 'Api\SearchSoftwareController@getSoftwaresByName');
    Route::post('/cookie', 'Api\SearchSoftwareController@setCookieExperience');
});

Route::group(['middleware' => 'web'], function () {

    Route::auth();

    Route::get('home', ['as' => 'home', 'uses' => function () {
        return view('home');
    }]);

    Route::get('social/login/redirect/{provider}', ['uses' => 'Auth\AuthController@redirectToProvider', 'as' => 'social.login']);
    Route::get('social/login/{provider}', 'Auth\AuthController@handleProviderCallback');

    Route::get('str/software_list', 'FavoritesController@index');
    Route::get('str/software_list/delete/all', ['uses' => 'FavoritesController@deleteAll', 'as' => 'delete.favorite.all']);
    Route::get('str/software_list/delete/{id}', ['uses' => 'FavoritesController@delete', 'as' => 'delete.favorite']);
    Route::get('str/software_list/add/{id}', ['uses' => 'FavoritesController@addFavorite', 'as' => 'add.favorite']);

    Route::get('software/mark/add', ['uses' => 'MarksController@addMark', 'as' => 'add.mark']);



    # ADMIN SECTION
    Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {

        Route::get('home', 'HomeController@index');

        # CATEGORIES
        Route::resource('kategorije', 'Admin\CategoryController');

        # USERS
        Route::resource('korisnici', 'Admin\UserController');

        # SOFTWARE
        Route::resource('software', 'Admin\SoftwareController');
        Route::post('software/search', 'Admin\SoftwareController@search');

        #DEAD LINKS
        Route::get('deadlinks', 'Admin\DeadLinksController@index');
        Route::get('deadlinks/check', 'Admin\DeadLinksController@checkLinks');
        Route::post('deadlinks/update/{id}', ['uses' => 'Admin\DeadLinksController@updateLink', 'as' => 'deadlinks.update']);
        Route::delete('deadlinks/delete/{id}', ['uses' => 'Admin\DeadLinksController@deleteSoftware', 'as' => 'deadlinks.delete']);
        Route::post('deadlinks/report/{id}', ['uses' => 'Admin\DeadLinksController@reportBrokenLink', 'as' => 'deadlinks.report']);

        #PROGRAM OF WEEK
        Route::get('week/programs', 'Admin\ProgramWeekController@index');
        Route::post('week/programs/add/{id}', ['uses' => 'Admin\ProgramWeekController@addProgram', 'as' => 'week.program.add']);

        #USER SOFTWARE
        Route::get('korisnici-software', 'AddSoftwareController@showUserSoftwares');
        Route::delete('korisnici-software/delete/{id}', ['uses' => 'AddSoftwareController@deleteUserSoftware', 'as' => 'user.software.delete']);
        Route::get('korisnici-software/accept/{id}', ['uses' => 'AddSoftwareController@acceptUserSoftware', 'as' => 'user.software.accept']);

        #CONTENT
        Route::get('content', 'Admin\ContentController@index');
        Route::post('content', 'Admin\ContentController@saveContent');

    });

    Route::get('/{category?}', 'PageController@home');
    Route::get('/{category}/{software}', 'PageController@details');

});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'korisnici';

    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'ime', 'prezime', 'username', 'password', 'dozvole', 'registriran'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'lozinka', 'remember_token',
    ];

    public function favorites() {
        return $this->belongsToMany('App\Software', 'favorites', 'korisnici_id', 'software_id');
    }

    public function marks() {
        return $this->belongsToMany('App\Software', 'ocjene', 'korisnici_id', 'software_id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(10);
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = $request->all();
        $user['password'] = bcrypt($request->password);
        $user['registriran'] = Carbon::now();
        User::create($user);
        return redirect('admin/korisnici');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $userUpdate = $request->all();
        $user = User::find($id);
        $user->update($userUpdate);
        return redirect('admin/korisnici');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::findOrFail($id)->delete();
        return redirect('admin/korisnici');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.default.layout')

@section('content')
    <div class="container">
        <h1>Kreiraj korisnika</h1>
        <form method="POST" action="{{ url('admin/korisnici') }}">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <input type="hidden" name="_token" value="{!! csrf_token() !!}">
            <div class="form-group">
                <label for="ime">Ime:</label>
                <input type="text" name="ime" class="form-control">
            </div>
            <div class="form-group">
                <label for="prezime">Prezime:</label>
                <input type="text" name="prezime" class="form-control">
            </div>
            <div class="form-group">
                <label for="username">Korisničko ime:</label>
                <input type="text" name="username" class="form-control">
            </div>
            <div class="form-group">
                <label for="password">Lozinka:</label>
                <input type="password" name="password" class="form-control">
            </div>
            <div class="form-group">
                <label for="role">Rola:</label>
                <select name="dozvole" class="form-control">
                    <option value="">Odaberi rolu</option>
                    <option value="1">User</option>
                    <option value="0">Administrator</option>
                </select>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary form-control">Kreiraj</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.default.layout')

@section('content')
    <div class="container">
        <h1>Ažuriraj korisnika</h1>
        <form method="POST" action="{{ route('admin.korisnici.update', [$user->id]) }}">
            <input type="hidden" name="_method" value="PUT">
            <input type="hidden" name="_token" value="{!! csrf_token() !!}">
            <div class="form-group">
                <label for="name">Ime:</label>
                <input type="text" name="ime" class="form-control" value="{{ $user->ime }}">
            </div>
            <div class="form-group">
                <label for="email">Prezime:</label>
                <input type="text" name="prezime" class="form-control" value="{{ $user->prezime }}">
            </div>
            <div class="form-group">
                <label for="city">Korisničko ime:</label>
                <input type="text" name="username" class="form-control" value="{{ $user->username }}">
            </div>
            <div class="form-group">
                <label for="role">Rola:</label>
                <select name="dozvole" class="form-control">
                    <option value="">Choose role</option>
                    @if($user->role == 1)
                        <option value="1" selected>User</option>
                        <option value="0">Administrator</option>
                    @else
                        <option value="1">User</option>
                        <option value="0" selected>Administrator</option>
                    @endif
                </select>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary form-control">Ažuriraj</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.default.layout')

@section('content')
    <div class="container">
        <h1>Korisnici</h1>
        <a href="{{url('admin/korisnici/create')}}" class="btn btn-success">Kreiraj korisnika</a>
        <hr>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>ID</th>
                <th>Ime</th>
                <th>Prezime</th>
                <th>Korisničko ime</th>
                <th>Datum registracije</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->ime }}</td>
                    <td>{{ $user->prezime }}</td>
                    <td>{{ $user->username }}</td>
                    <td>{{ $user->registriran }}</td>
                    <td><a href="{{url('admin/korisnici',$user->id)}}" class="btn btn-primary">Vidi</a></td>
                    <td><a href="{{route('admin.korisnici.edit',$user->id)}}" class="btn btn-warning">Ažuriraj</a></td>
                    <td>
                        <form action="{{ route('admin.korisnici.destroy', [$user->id]) }}" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button type="submit" class="btn btn-danger">Obriši</button>
                        </form>
                    </td>
                </tr>
            @endforeach

            </tbody>

        </table>
        <div style="text-align: center">
            {!! $users->render() !!}
        </div>

    </div>
@endsection

resources/views/admin/users/show.blade.php
@extends('admin.default.layout')

@section('content')
    <div class="container">
        <h1>Korisnik pogled</h1>

        <form class="form-horizontal">
            <div class="form-group">
                <label for="id" class="col-sm-2 control-label">ID</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="id" placeholder="{{$user->id}}" readonly>
                </div>
            </div>
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">Ime</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="name" placeholder="{{$user->ime}}" readonly>
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-sm-2 control-label">Prezime</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="email" placeholder="{{$user->prezime}}" readonly>
                </div>
            </div>
            <div class="form-group">
                <label for="city" class="col-sm-2 control-label">Korisničko ime</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="city" placeholder="{{$user->username}}" readonly>
                </div>
            </div>
            <div class="form-group">
                <label for="country" class="col-sm-2 control-label">Rola</label>
                @if($user->dozvole == 0)
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="country" placeholder="Administrator" readonly>
                    </div>
                    @else
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="country" placeholder="User" readonly>
                    </div>
                    @endif

            </div>
            <div class="form-group">
                <label for="birth_date" class="col-sm-2 control-label">Datum registracije</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="birth_date" placeholder="{{$user->registriran}}" readonly>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <a href="{{ url('admin/korisnici')}}" class="btn btn-primary">Natrag</a>
                </div>
            </div>
        </form>

    </div>
@endsection