app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
Route::get('mail', 'MailController@sendMail');
Route::get('test', 'TestController@index');
/* PAGES */
Route::post('changelocale', ['as' => 'changelocale', 'uses' => 'TranslationController@changeLocale']);
Route::post('dodaj', ['as' => 'dodaj.software', 'uses' => 'AddSoftwareController@addSoftware']);
Route::post('contact', 'ContactController@contact');
Route::get('RSS', 'RssFeedController@getRSS');
Route::get('/o-nama', 'PageController@aboutUs');
Route::get('str/sto-se-skida', 'PageController@whatIsDownloaded');
Route::get('/dodaj', 'PageController@addSoftware');
Route::get('/logout', 'Auth\AuthController@logout');
Route::get('/top-50', 'PageController@topPrograms');

Route::get('/downloads/{id}', ['uses' => 'DownloadController@download', 'as' => 'download.software']);
Route::get('/downloads/m/{id}', ['uses' => 'DownloadController@download', 'as' => 'download.software.mirror']);
Route::get('/downloads/download/{id}', ['uses' => 'DownloadController@downloadSoftware', 'as' => 'download.software.path']);
Route::get('/downloads/download/server/{id}', ['uses' => 'DownloadController@downloadSoftwareFromServer', 'as' => 'download.software.path.server']);

Route::get('/search', 'SearchController@index');
Route::get('/search/{software}', 'SearchController@show');
/* API */
Route::group(['prefix' => 'api/v1'], function() {
    Route::get('/search/{name}', 'Api\SearchSoftwareController@searchByName');
    Route::get('/getSoftwares/{name}', 'Api\SearchSoftwareController@getSoftwaresByName');
    Route::post('/cookie', 'Api\SearchSoftwareController@setCookieExperience');
});

Route::group(['middleware' => 'web'], function () {

    Route::auth();

    Route::get('home', ['as' => 'home', 'uses' => function () {
        return view('home');
    }]);

    Route::get('social/login/redirect/{provider}', ['uses' => 'Auth\AuthController@redirectToProvider', 'as' => 'social.login']);
    Route::get('social/login/{provider}', 'Auth\AuthController@handleProviderCallback');

    Route::get('str/software_list', 'FavoritesController@index');
    Route::get('str/software_list/delete/all', ['uses' => 'FavoritesController@deleteAll', 'as' => 'delete.favorite.all']);
    Route::get('str/software_list/delete/{id}', ['uses' => 'FavoritesController@delete', 'as' => 'delete.favorite']);
    Route::get('str/software_list/add/{id}', ['uses' => 'FavoritesController@addFavorite', 'as' => 'add.favorite']);

    Route::get('software/mark/add', ['uses' => 'MarksController@addMark', 'as' => 'add.mark']);



    # ADMIN SECTION
    Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {

        Route::get('home', 'HomeController@index');

        # CATEGORIES
        Route::resource('kategorije', 'Admin\CategoryController');

        # USERS
        Route::resource('korisnici', 'Admin\UserController');

        # SOFTWARE
        Route::resource('software', 'Admin\SoftwareController');
        Route::post('software/search', 'Admin\SoftwareController@search');

        #DEAD LINKS
        Route::get('deadlinks', 'Admin\DeadLinksController@index');
        Route::get('deadlinks/check', 'Admin\DeadLinksController@checkLinks');
        Route::post('deadlinks/update/{id}', ['uses' => 'Admin\DeadLinksController@updateLink', 'as' => 'deadlinks.update']);
        Route::delete('deadlinks/delete/{id}', ['uses' => 'Admin\DeadLinksController@deleteSoftware', 'as' => 'deadlinks.delete']);
        Route::post('deadlinks/report/{id}', ['uses' => 'Admin\DeadLinksController@reportBrokenLink', 'as' => 'deadlinks.report']);

        #PROGRAM OF WEEK
        Route::get('week/programs', 'Admin\ProgramWeekController@index');
        Route::post('week/programs/add/{id}', ['uses' => 'Admin\ProgramWeekController@addProgram', 'as' => 'week.program.add']);

        #USER SOFTWARE
        Route::get('korisnici-software', 'AddSoftwareController@showUserSoftwares');
        Route::delete('korisnici-software/delete/{id}', ['uses' => 'AddSoftwareController@deleteUserSoftware', 'as' => 'user.software.delete']);
        Route::get('korisnici-software/accept/{id}', ['uses' => 'AddSoftwareController@acceptUserSoftware', 'as' => 'user.software.accept']);

        #CONTENT
        Route::get('content', 'Admin\ContentController@index');
        Route::post('content', 'Admin\ContentController@saveContent');

    });

    Route::get('/{category?}', 'PageController@home');
    Route::get('/{category}/{software}', 'PageController@details');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'kategorije';

    public $timestamps = false;

    protected $fillable = ['imeKategorije', 'nameKategorije', 'imeUrl', 'nameUrl'];

    public function softwares()
    {
        return $this->hasMany('App\Software', 'kategorija');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(10);
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'imeKategorije' => 'required|max:255',
            'nameKategorije' => 'required|max:255',
        ]);

        $category = $request->all();
        $category['imeUrl'] = parseCategoryName($category['imeKategorije']);
        $category['nameUrl'] = parseCategoryName($category['nameKategorije']);
        Category::create($category);
        return redirect('admin/kategorije');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);
        return view('admin.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $categoryUpdate = $request->all();
        $category = Category::find($id);
        $category->update($categoryUpdate);
        return redirect('admin/kategorije');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::findOrFail($id)->delete();
        return redirect('admin/kategorije');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.default.layout')

@section('content')
    <div class="container">
        <h1>Kreiraj kategoriju</h1>
        <form method="POST" action="{{ url('admin/kategorije') }}">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <input type="hidden" name="_token" value="{!! csrf_token() !!}">
            <div class="form-group">
                <label for="imeKategorije">Naziv kategorije (HR):</label>
                <input type="text" name="imeKategorije" class="form-control">
            </div>
            <div class="form-group">
                <label for="nameKategorije">Naziv kategorije (ENG):</label>
                <input type="text" name="nameKategorije" class="form-control">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary form-control">Kreiraj</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.default.layout')

@section('content')
    <div class="container">
        <h1>Update User</h1>
        <form method="POST" action="{{ route('admin.kategorije.update', [$category->id]) }}">
            <input type="hidden" name="_method" value="PUT">
            <input type="hidden" name="_token" value="{!! csrf_token() !!}">
            <div class="form-group">
                <label for="name">Naziv kategorije (HR):</label>
                <input type="text" name="imeKategorije" class="form-control" value="{{ $category->imeKategorije }}">
            </div>
            <div class="form-group">
                <label for="email">Naziv kategorije (ENG):</label>
                <input type="text" name="nameKategorije" class="form-control" value="{{ $category->nameKategorije }}">
            </div>
            <div class="form-group">
                <label for="city">Ime Url:</label>
                <input type="text" name="imeUrl" class="form-control" value="{{ $category->imeUrl }}">
            </div>
            <div class="form-group">
                <label for="country">Name Url:</label>
                <input type="text" name="nameUrl" class="form-control" value="{{ $category->nameUrl }}">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary form-control">Save</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.default.layout')

@section('content')
    <div class="container">
        <h1>Kategorije</h1>
        <a href="{{url('admin/kategorije/create')}}" class="btn btn-success">Kreiraj kategoriju</a>
        <hr>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>ID</th>
                <th>Naziv kategorije (HR)</th>
                <th>Naziv kategorije (ENG)</th>
                <th colspan="3">Akcije</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($categories as $category)
                <tr>
                    <td>{{ $category->id }}</td>
                    <td>{{ $category->imeKategorije }}</td>
                    <td>{{ $category->nameKategorije }}</td>
                    <td><a href="{{url('admin/kategorije',$category->id)}}" class="btn btn-primary">Vidi</a></td>
                    <td><a href="{{route('admin.kategorije.edit',$category->id)}}" class="btn btn-warning">Ažuriraj</a></td>
                    <td>
                        <form action="{{ route('admin.kategorije.destroy', [$category->id]) }}" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button type="submit" class="btn btn-danger">Obriši</button>
                        </form>
                    </td>
                </tr>
            @endforeach

            </tbody>

        </table>
        <div style="text-align: center">
            {!! $categories->render() !!}
        </div>

    </div>
@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.default.layout')

@section('content')
    <div class="container">
        <h1>Kategorija pogled</h1>

        <form class="form-horizontal">
            <div class="form-group">
                <label for="id" class="col-sm-2 control-label">ID</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="id" placeholder="{{$category->id}}" readonly>
                </div>
            </div>
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">Naziv kategorije (HR)</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="name" placeholder="{{$category->imeKategorije}}" readonly>
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-sm-2 control-label">Naziv kategorije (ENG)</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="email" placeholder="{{$category->nameKategorije}}" readonly>
                </div>
            </div>
            <div class="form-group">
                <label for="city" class="col-sm-2 control-label">Friendly url (HR)</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="city" placeholder="{{$category->imeUrl}}" readonly>
                </div>
            </div>
            <div class="form-group">
                <label for="city" class="col-sm-2 control-label">Friendly url (ENG)</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="city" placeholder="{{$category->nameUrl}}" readonly>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <a href="{{ url('admin/kategorije')}}" class="btn btn-primary">Back</a>
                </div>
            </div>
        </form>

    </div>
@endsection